import "./globals.css";

import { Montserrat } from "next/font/google";

import Footer from "@/components/Footer";
import localFont from "@next/font/local";

import Header from "../components/Header";

import type { Metadata } from "next";
// Fonts
const montserrat = Montserrat({ subsets: ["latin"], style: ["normal", "italic"], weight: ["400", "500", "700"], variable: "--font-montserrat" });
const clashDisplay = localFont({ src: "../../public/fonts/ClashDisplay.ttf", variable: "--font-clash" });

export const metadata: Metadata = {
	title: "GetLinked",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={`${clashDisplay.variable} ${montserrat.variable} bg-backgroundColor`}>
			<body className="relative">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
